from __future__ import annotations

import numpy as np
from OpenGL.GL import (
    glMultMatrixf,
    glPopMatrix,
    glPushMatrix,
    glTranslatef,
)
from OpenGL.GLU import (
    gluCylinder,
    gluDeleteQuadric,
    gluNewQuadric,
    gluSphere,
)


def draw_sphere(
    position: np.ndarray,
    radius: float = 3.0,
    slices: int = 20,
    stacks: int = 20,
) -> None:
    """Draw a sphere centered at an XYZ position."""

    quadric = gluNewQuadric()

    glPushMatrix()
    glTranslatef(*position)
    gluSphere(quadric, radius, slices, stacks)
    glPopMatrix()

    gluDeleteQuadric(quadric)


def alignment_matrix(direction: np.ndarray) -> np.ndarray:
    """
    Rotate local +Z to match the requested direction.

    Cylinders generated by GLU extend along local +Z.
    """

    z_axis = direction / np.linalg.norm(direction)
    reference = np.array([0.0, 1.0, 0.0])

    # Avoid a degenerate cross product.
    if abs(np.dot(z_axis, reference)) > 0.999:
        reference = np.array([1.0, 0.0, 0.0])

    x_axis = np.cross(reference, z_axis)
    x_axis /= np.linalg.norm(x_axis)

    y_axis = np.cross(z_axis, x_axis)

    matrix = np.eye(4, dtype=np.float32)
    matrix[:3, 0] = x_axis
    matrix[:3, 1] = y_axis
    matrix[:3, 2] = z_axis

    return matrix


def draw_cylinder(
    start: np.ndarray,
    end: np.ndarray,
    radius: float = 2.0,
    slices: int = 20,
) -> None:
    """Draw a cylinder between two XYZ points."""

    direction = np.asarray(end) - np.asarray(start)
    length = float(np.linalg.norm(direction))

    if length == 0.0:
        return

    transform = alignment_matrix(direction)
    quadric = gluNewQuadric()

    glPushMatrix()
    glTranslatef(*start)

    # OpenGL expects column-major matrix data.
    glMultMatrixf(transform.T)

    gluCylinder(
        quadric,
        radius,
        radius,
        length,
        slices,
        1,
    )

    glPopMatrix()
    gluDeleteQuadric(quadric)


def draw_chain(
    joints: np.ndarray,
    joint_radius: float = 3.0,
    link_radius: float = 2.0,
) -> None:
    """Draw spheres at joints and cylinders between them."""

    for joint in joints:
        draw_sphere(joint, joint_radius)

    for start, end in zip(joints[:-1], joints[1:]):
        if not np.allclose(start, end):
            draw_cylinder(start, end, link_radius)